# Generated by Django 4.0.3 on 2022-04-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_date_alter_blogs_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(),
        ),
    ]
